# Generated by Django 5.1.5 on 2025-10-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MC_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='serving_size',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='serving_size_unit',
            field=models.CharField(choices=[('g', 'gram'), ('ml', 'milliliter'), ('pc', 'piece'), ('oz', 'ounce'), ('tbsp', 'tablespoon'), ('tsp', 'teaspoon')], default='g', max_length=10),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='serving_size_value',
            field=models.FloatField(default=0, help_text='Amount of one serving (e.g., 100)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.FloatField(),
        ),
    ]
