# Generated by Django 5.1.5 on 2025-10-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MC_App', '0002_remove_ingredient_serving_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='servings_per_container',
            field=models.FloatField(default=0, help_text='How many servings are in one container'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='calories',
            field=models.FloatField(help_text='Per serving'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='carbs',
            field=models.FloatField(help_text='Per serving'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fat',
            field=models.FloatField(help_text='Per serving'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.FloatField(help_text='Price of the whole container'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='protein',
            field=models.FloatField(help_text='Per serving'),
        ),
    ]
