# Generated by Django 5.1.5 on 2025-10-26 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MC_App', '0004_alter_recipe_name_alter_recipeitem_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeitem',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='MC_App.recipe'),
        ),
    ]
